<?php

/**
 * Uruguay cities
 * 
 * Listado de ciudades de Uruguay organizadas por departamento.
 */
global $cities;
$cities['UY'] = array(
	'UY-AR' => array(
		'Artigas',
		'B Rivera',
		'Baltasar Brum',
		'Barrio las Piedras',
		'Bella Unión',
		'Bernabe Rivera',
		'Cainsa',
		'Cainza Campo 3',
		'Calnu',
		'Calpica Itacumbu',
		'Catalan Grande',
		'Catalan Volcan',
		'Cerrito',
		'Cerro Ejido',
		'Cerro San Eugenio',
		'Cerro Signorelli',
		'Chiflero',
		'Colonia Estrella',
		'Colonia Mones Quintela',
		'Colonia Palma',
		'Colonia Pintado',
		'Coronado',
		'Cuareim',
		'Cuaro',
		'Diego Lamas',
		'Estacion Cuaro',
		'Estiba',
		'Fagundez',
		'Franquia',
		'Guayuvira',
		'Guyubira',
		'Javier de Viana',
		'La Bolsa',
		'Las Piedras',
		'Lenguazo',
		'Meneses',
		'Mones Quintela',
		'Paguero',
		'Palma Sola',
		'Paredón',
		'Paso Campamento',
		'Paso Farías',
		'Paso de León',
		'Paso de Ramos',
		'Paso de la Cruz',
		'Patitas',
		'Piedra Pintada',
		'Pintadito',
		'Pintado',
		'Pintado Grande',
		'Port. de Hierro y Campodónico',
		'Rincón de Pacheco',
		'Sarandi de Cuaro',
		'Sarandi de Yacuy',
		'Sequeira',
		'Tamanduá',
		'Tarumán',
		'Tomás Gomensoro',
		'Topador',
		'Zanja Aruera'
	),
	'UY-CA' => array(
		'Aeropuerto Internacional de Carrasco',
		'Aguas Corrientes',
		'Altos de la Tahona',
		'Araminda',
		'Argentino',
		'Atlántida',
		'Barra de Carrasco',
		'Barrio Copola',
		'Barrio Obrero',
		'Barrio Remanso',
		'Barrio la Lucha',
		'Barros Blancos',
		'Bello Horizonte',
		'Biarritz',
		'Blanco',
		'Bolivar',
		'Bosque de Solymar',
		'Camino Al Paso del Andaluz',
		'Campo Militar',
		'Canelones',
		'Capitan J A Artigas',
		'Carmel',
		'City Golf',
		'City Park',
		'Ciudad de la Costa',
		'Colinas de Carrasco',
		'Colinas de Solymar',
		'Colonia Nicolich',
		'Costa Azul',
		'Costa y Guillamón',
		'Costa de Pando Olmos',
		'Costa de Pando San Jacinto',
		'Cruz de los Caminos',
		'Cuchilla Alta',
		'Cumbres de Carrasco',
		'Doctor Francisco Soca',
		'El Bosque',
		'El Bosque de Carrasco',
		'El Bosque de Solymar',
		'El Galeón',
		'El Palmar',
		'El Pinar',
		'Empalme Olmos',
		'Estacion Atlantida',
		'Estacion Castellanos',
		'Estacion Migues',
		'Estacion Pedrera',
		'Estacion Piedras de Afilar',
		'Estacion Soudriers',
		'Estacion Tapia',
		'Estacion la Floresta',
		'Estanque de Pando',
		'Fortin de Santa Rosa',
		'Fracc. Cno. Andaluz y R.84',
		'Fracc. Progreso',
		'Fracc. Sobre Ruta 74',
		'Fraccionamiento Progreso',
		'Fraccionamiento Sobre Ruta 74',
		'Francisco Soca',
		'Guazuvira',
		'Guazuvira Nuevo',
		'Haras del Lago',
		'Instituto Adventista',
		'Jardines de Pando',
		'Jaureguiberry',
		'Joaquin Suarez',
		'Juanico',
		'La Asuncion',
		'La Floresta',
		'La Montaesa',
		'La Paz',
		'La Tuna',
		'Lago Jardin del Bosque',
		'Lagomar',
		'Las Higueritas',
		'Las Piedras',
		'Las Toscas',
		'Las Vegas',
		'Lomas de Carrasco',
		'Lomas de Solymar',
		'Los Cerrillos',
		'Los Titanes',
		'Marindia',
		'Médanos de Solymar',
		'Migues',
		'Montes',
		'Montes de Solymar',
		'Neptunia',
		'Olmos',
		'Pando',
		'Parada Cabrera',
		'Parque Carrasco',
		'Parque Miramar',
		'Parque de Solymar',
		'Parque del Plata',
		'Paso Carrasco',
		'Paso Espinosa',
		'Paso Palomeque',
		'Paso de Pache',
		'Paso de la Cadena',
		'Paso de las Toscas',
		'Paso del Toro',
		'Piedra del Toro',
		'Piedras de Afilar',
		'Pinamar',
		'Pinares de Solymar',
		'Pine Park',
		'Pinepark',
		'Progreso',
		'Pueblo Castellanos',
		'Quinta los Horneros',
		'Quintas del Bosque',
		'S Bautista',
		'Salinas',
		'San Antonio',
		'San Bautista',
		'San Jacinto',
		'San Jose de Carrasco',
		'San Luis',
		'San Ramon',
		'Santa Ana',
		'Santa Lucia',
		'Santa Lucia del Este',
		'Santa Rosa',
		'Sauce',
		'Seis Hermanos',
		'Shangrila',
		'Sofia Santos',
		'Solymar',
		'Soudriers',
		'Suarez',
		'Tala',
		'Totoral del Sauce',
		'Vejigas de San Ramon',
		'Viaducto Canelones',
		'Viejo Molino San Bernardo',
		'Viejo Molino y San Bernardo',
		'Villa Aeroparque',
		'Villa Arejo',
		'Villa Argentina',
		'Villa Encantada',
		'Villa Felicidad',
		'Villa Hadita',
		'Villa Juana',
		'Villa Juanita',
		'Villa Paz S.a.',
		'Villa San Cono',
		'Villa San Felipe',
		'Villa San Jose',
		'Villa el Tato'
	),
	'UY-CL' => array(
		'Acegua',
		'Almeida',
		'Angapire',
		'Arachania',
		'Arbolito',
		'Arevalo',
		'Arroyo Malo',
		'Asperezas',
		'Baado de Medina',
		'Balneario Lago Merin',
		'Barrio Lopez Benitez',
		'Barrio la Vinchuca',
		'Casa de las Cronicas',
		'Caserio las Caas',
		'Centurion',
		'Cerro de las Cuentas',
		'Cuchilla del Carmen',
		'Escuela de Agronomia',
		'Esperanza',
		'Fraile Muerto',
		'Hipodromo',
		'Isidoro Noblia',
		'Juncal',
		'La Pedrera',
		'Lago Merin',
		'Mangrullo',
		'Melo',
		'Nando',
		'Paso Almeida',
		'Placido Rosas',
		'Poblado Uruguay',
		'Presidente Doctor Getulio Vargas',
		'Pueblo Almeida',
		'Pueblo Juncal',
		'Puntas de Molles',
		'Quebracho',
		'Ramon Trigo',
		'Rio Branco',
		'Soto Goro',
		'Toledo',
		'Tres Islas',
		'Tupambae',
		'Wenceslao Silvera'
	),
	'UY-CO' => array(
		'Agraciada',
		'Arrivillaga',
		'Artilleros',
		'Balneario Artilleros',
		'Balneario Britopolis',
		'Balneario Santa Ana',
		'Balneario Zagarzau',
		'Balneario Zagarzazu',
		'Barker',
		'Barker Norte',
		'Barrancas Coloradas',
		'Barrio Olimpico',
		'Belgrano Norte',
		'Belgrano Sur',
		'Blanca Arena',
		'Boca del Rosario',
		'Boca del Rosario Oeste',
		'Bonjour',
		'Brisas del Plata',
		'Buena Hora',
		'Campana',
		'Carmelo',
		'Caserio el Cerro',
		'Cerro Carmelo',
		'Cerro de las Armas',
		'Cerros Negros',
		'Cerros de San Juan',
		'Chico Torino',
		'Colonia Arrue',
		'Colonia Cosmopolita',
		'Colonia Espaola',
		'Colonia Estrella',
		'Colonia Miguelete',
		'Colonia Peirano',
		'Colonia Quevedo',
		'Colonia Sarandi',
		'Colonia Suiza',
		'Colonia Talice',
		'Colonia Valdense',
		'Colonia del Sacramento',
		'Conchillas',
		'Concordia',
		'Costa de Colla Al Este',
		'Costa de Rosario',
		'Costa de Tarariras',
		'Costa de Vacas',
		'Costa del Navarro',
		'Costas de Juan Gonzalez',
		'Costas de Polonia',
		'Costas de San Juan',
		'Cufre',
		'El Chileno',
		'El Cuadro',
		'El Ensueo',
		'El Faro',
		'El Quinton',
		'El Semillero',
		'Estacion Estanzuela',
		'Estacion Experimental "la Estanzuela"',
		'Fcio Sanchez',
		'Florencio Sanchez',
		'Gil',
		'Juan Carlos Caseros',
		'Juan Gonzalez',
		'Juan Jackson',
		'Juan Lacaze',
		'La Estanzuela',
		'La Horqueta',
		'La Paz',
		'La Sierra',
		'Laguna de los Patos',
		'Las Chispas',
		'Las Flores',
		'Los Pinos',
		'Manantiales',
		'Martin Chico',
		'Martin Chico de Conchillas',
		'Media Agua',
		'Miguelete de Conchillas',
		'Minas de Narancio',
		'Minuano y Sauce',
		'Molles de Miguelete',
		'Nueva Helvecia',
		'Nueva Palmira',
		'Ombues de Lavalle',
		'P.astillero',
		'Paraje Minuano',
		'Paso Antolin',
		'Paso Birriel',
		'Paso Hospital',
		'Paso Hospital Manantiales',
		'Paso Morlan',
		'Paso Quicho',
		'Paso de la Quinta',
		'Pastoreo',
		'Picada de Benitez',
		'Piedra Chata',
		'Piedra de los Indios',
		'Piedras Blancas',
		'Playa Azul',
		'Playa Britopolis',
		'Playa Fomento',
		'Playa Parant',
		'Polanco',
		'Polancos',
		'Pueblo Gil',
		'Puerto Concordia',
		'Puerto Ingles',
		'Puerto Platero',
		'Puerto Rosario',
		'Punta Francesa',
		'Puntas de Juan Gonzalez',
		'Puntas de Melo',
		'Puntas de San Juan',
		'Puntas de San Pedro',
		'Puntas del Riachuelo',
		'Puntas del Sauce',
		'Quinton',
		'Radial Hernandez',
		'Radial Rosario',
		'Real de Vera',
		'Reducto',
		'Resguardo Cufre',
		'Riachuelo',
		'Rincón del Rey',
		'Rosario',
		'Rosario y Colla',
		'San Juan',
		'San Luis',
		'San Luis Sanchez',
		'San Luis de Tarariras',
		'San Pedro',
		'San Pedro Norte',
		'San Pedro de Arriba',
		'San Roque',
		'Santa Ana',
		'Santa Regina',
		'Santa Rosa',
		'Sarandi Campana',
		'Tarariras',
		'Terminal',
		'Tomás Bell',
		'Tres Esquinas',
		'Viboras',
		'Viboras y Vacas',
		'Villa Pancha',
		'Zagarzazu',
		'Zunin'
	),
	'UY-DU' => array(
		'Abella',
		'Aguas Buenas',
		'Arroyo de los Perros',
		'Barrancas Coloradas',
		'Batoví',
		'Baygorria',
		'Blanquillo',
		'Blanquillo Al Oeste',
		'Caballero',
		'Capilla Farruco',
		'Capilla de Farruco',
		'Carlos Reyles',
		'Ceibal',
		'Cerrezuelo',
		'Cerro Chato',
		'Cerro Convento',
		'Chacras de Durazno',
		'Chileno',
		'Chileno Chico',
		'Chileno Grande (aguero)',
		'Costa de Cuadra',
		'Cuchilla de Ramirez',
		'Cuchilla del Rincón',
		'De Dios',
		'Durazno',
		'Elias Regules',
		'Estacion Chileno',
		'Estacion Parish',
		'Feliciano',
		'Fonseca',
		'Higueras de Carpinteria',
		'La Alegria',
		'La Mazamorra',
		'La Paloma',
		'Las Acacias',
		'Las Caas',
		'Las Palmas',
		'Las Tunas',
		'Los Agregados',
		'Los Tapes',
		'Maestre Campo',
		'Malbajar Este',
		'Malbajar Oeste',
		'María Cejas',
		'Mariscala',
		'Mariscala del Carmen',
		'Molles Chico',
		'Molles de Quinteros',
		'Municipio de Durazno',
		'Ombues de Oribe',
		'Parada Sur',
		'Parish',
		'Paso Ramirez',
		'Paso Real de Carpinteria',
		'Paso Tejera',
		'Paso de Aguirre',
		'Paso de Castro',
		'Paso del Medio las Palmas',
		'Pueblo Centenario',
		'Pueblo de Alvarez',
		'Puglia',
		'Puntas de Carpinteria',
		'Puntas de Herrera',
		'Puntas de Malbajar',
		'Rincón de los Tapes',
		'Rolon',
		'Rossell y Rius',
		'Salinas',
		'Salinas Chico',
		'San Jorge',
		'Sandu Chico',
		'Santa Bernardina',
		'Sarandi de Rio Negro',
		'Sarandi de la China',
		'Sarandi del Rio Negro',
		'Sarandi del Yi',
		'Sauce de Herrera',
		'Sauce del Yi',
		'Tala de Mariscala',
		'Tejera',
		'Verdun',
		'Villa del Carmen',
		'Villasboas'
	),
	'UY-FS' => array(
		'Ahogados',
		'Andresito',
		'Arenal Chico',
		'Arenal Grande',
		'Arroyo Malo',
		'Cerro Colorado',
		'Chacras',
		'Chacras de Borghi',
		'Colonia Alemana',
		'Costas de San Jose',
		'Costas del Tala',
		'Cuchilla de Villasboas',
		'El Coronilla',
		'El Totoral',
		'Ferrizo',
		'Ismael Cortinas',
		'Juan Jose Castro',
		'La Alianza',
		'La Casilla',
		'La Cordobesa',
		'La Guardia',
		'Marincho',
		'Paso  de Lugo',
		'Paso Hondo',
		'Pueblo Pintos',
		'Puntas de Chamanga',
		'Puntas de Marincho',
		'Puntas de San Jose',
		'Puntas de Sarandi',
		'Puntas del Corral de Piedra',
		'Puntas del Sauce',
		'Rincón del Palacio',
		'San Gregorio de Flores',
		'Santa Adelaida',
		'Sarandi',
		'Talas de Maciel',
		'Trinidad',
		'Villa Pastora',
		'Villasboas'
	),
	'UY-FD' => array(
		'25 de Agosto',
		'25 de Mayo',
		'Alejandro Gallinal',
		'Arrayan',
		'Arroyo Chamizo',
		'Arroyo Latorre',
		'Arroyo Monzon',
		'Arroyo Pelado',
		'Arroyo de los Negros',
		'Arteaga',
		'Barcelo',
		'Barra Molles del Timote',
		'Barra Sauce de Mansavillagra',
		'Berrondo',
		'Calleri',
		'Candil',
		'Capilla del Sauce',
		'Cardal',
		'Caserio la Fundacion',
		'Casupa',
		'Cerro Chato',
		'Cerro Colorado',
		'Cerro de la Macana',
		'Cerros de Florida',
		'Chacras de Florida',
		'Chacras del Pintado',
		'Chamizo',
		'Chamizo Chico',
		'Chilcas',
		'Chingolas',
		'Colonia Sanchez',
		'Corral de Piedra',
		'Costa de Arias',
		'Costa de Illescas',
		'Costa de Parana',
		'Costa de la Cruz',
		'Costa del Tala',
		'Costas de Arias',
		'Costas de Chamizo',
		'Costas de Chamizo Grande',
		'Costas de Maciel',
		'Costas de Santa Lucia Chico',
		'Costas del Amarillo',
		'Costas del Pintado',
		'Costas del Santa Lucia Grande',
		'Cuchilla Santo Domingo',
		'Dr. A. Gallinal',
		'Estacion Capilla del Sauce',
		'Estacion Montecoral',
		'Estacion Palermo',
		'Estacion Pintado',
		'Ferrer',
		'Florida',
		'Fray Marcos',
		'Goi',
		'Hernandarias',
		'Illescas',
		'Independencia',
		'Jose Batlle y Ordoez',
		'Jose Batlle y Ordonez',
		'Juncal',
		'La Cimbra',
		'La Cruz',
		'La Escobilla',
		'La Macana',
		'La Palma',
		'La Victoria',
		'Las Chilcas',
		'Las Piedritas',
		'Mansavillagra',
		'Mendoza Chico',
		'Mendoza Grande',
		'Molles del Pescado',
		'Molles del Timote',
		'Montecoral',
		'Nico Perez',
		'Palermo',
		'Pantanoso de Castro',
		'Paso Calleros',
		'Paso Real de Mansavillagra',
		'Paso Vela',
		'Paso de los Novillos',
		'Piedra Campana',
		'Piedras Coloradas',
		'Pintado',
		'Polanco del Yi',
		'Pueblo Ferrer',
		'Pueblo de los Morochos',
		'Puente de Mendoza',
		'Puntas de Calleros',
		'Puntas de Chamame',
		'Puntas de Chamizo',
		'Puntas de Illescas',
		'Puntas de Maciel',
		'Puntas de Mansavillagra',
		'Puntas de Sarandi',
		'Puntas de Sauce de Maciel',
		'Puntas de la Escobilla',
		'Puntas del Arroyo Latorre',
		'Reboledo',
		'Rincón Sauce del Yi',
		'Rincón de Vignoli',
		'Rincón de los Camilos',
		'San Gabriel',
		'San Geronimo',
		'San Juan',
		'San Pedro de Timote',
		'Santa Clara',
		'Santa Teresa',
		'Sarandi Grande',
		'Sauce de Maciel',
		'Sauce de Villanueva',
		'Sauce del Yi',
		'Tabare',
		'Tala de Castro',
		'Tala de Maciel',
		'Talita',
		'Tornero',
		'Urioste',
		'Valentines',
		'Vignoli',
		'Villa Hipica',
		'Villa Vieja'
	),
	'UY-LA' => array(
		'19 de Junio',
		'Abra de Zabaleta',
		'Aguas Blancas',
		'Alonso',
		'Aramendia',
		'Arequita',
		'Arroyo de los Patos',
		'Arroyo del Medio',
		'Azucar',
		'Barra de los Chanchos',
		'Barrancas',
		'Barriga Negra',
		'Barrio la Coronilla - Ancap',
		'Blanes Viale',
		'Campanero',
		'Canteras del Verdun',
		'Carnales',
		'Casupa',
		'Casupa Chico',
		'Cerro Pelado',
		'Chamame',
		'Colon',
		'Costa del Lenguazo',
		'Costas de Corrales',
		'Costas del Soldado',
		'El Alto',
		'El Perdido',
		'El Soldado',
		'El Tigre',
		'Espuelitas',
		'Estacion Andreoni',
		'Estacion Ortiz',
		'Estacion Solis',
		'Gaetan (cuchilla de Carbajal)',
		'Godoy',
		'Gutierrez',
		'Higueritas',
		'Illescas',
		'Jose Batlle y Ordoez',
		'Jose Batlle y Ordonez',
		'Jose Pedro Varela',
		'La Cuchilla',
		'La Plata',
		'Ladrillos',
		'Larrosa',
		'Las Achiras',
		'Los Tapes',
		'Manguera Azul',
		'Marco de los Reyes',
		'Mariscala',
		'Marmaraja',
		'Minas',
		'Molles de Aigua',
		'Molles de Caada Grande',
		'Molles del Sauce',
		'Ombues de Bentancor',
		'Ortiz',
		'Ortiz Castro',
		'Paso Arbelo',
		'Paso de Mesa',
		'Paso de los Troncos',
		'Piraraja',
		'Polanco',
		'Polanco Norte',
		'Polanco Sur',
		'Pororo',
		'Puente de Marmaraja',
		'Puntas de Barriga Negra',
		'Puntas de Polanco',
		'Puntas de San Francisco',
		'Puntas de Santa Lucia',
		'Puntas de Solis',
		'Puntas de Vejigas',
		'Puntas de los Chanchos',
		'Puntas del Perdido',
		'Retamosa',
		'Rincón de Cebollati',
		'Rincón de Mariscala',
		'Rincón de Silva',
		'Roldan',
		'San Francisco de las Sierras',
		'Santa Lucia',
		'Sarandi de Gutierrez',
		'Sauce de Aigua',
		'Sauce de Olimar Chico',
		'Sierras Blancas',
		'Soldado',
		'Solis',
		'Solis Grande',
		'Solis de Mataojo',
		'Tapes Chico',
		'Tapes Grande',
		'Valle de Solis',
		'Vejigas',
		'Velazquez',
		'Verdun',
		'Villa Serrana',
		'Villa del Rosario',
		'Zapican'
	),
	'UY-MA' => array(
		'Aigua',
		'Arenas de Jose Ignacio',
		'Balneario Buenos Aires',
		'Barra de Maldonado',
		'Barra de Portezuelo',
		'Barrio Hipodromo',
		'Bella Vista',
		'Buenos Aires',
		'Canteras de Marelli',
		'Cerro Pelado',
		'Cerros Azules',
		'Chihuahua',
		'Eden Rock',
		'El Chorro',
		'El Eden',
		'El Quijote',
		'El Tesoro',
		'Faro Jose Ignacio',
		'Faro Jose Ignacio Norte',
		'Garzon',
		'Gerona',
		'Gregorio Aznarez',
		'La Barra',
		'La Capuera',
		'La Falda',
		'La Sonrisa',
		'Laguna Blanca',
		'Las Cumbres',
		'Las Flores',
		'Las Flores - Estacion',
		'Los Aromos',
		'Los Corchos',
		'Los Talas',
		'Maldonado',
		'Manantiales',
		'Nueva Carrara',
		'Ocean Park',
		'Pan de Azucar',
		'Parque Medina',
		'Pinares - las Delicias',
		'Piriapolis',
		'Playa Grande',
		'Playa Hermosa',
		'Playa Verde',
		'Pueblo Solis',
		'Pueblo las Flores',
		'Punta Ballena',
		'Punta Colorada',
		'Punta Negra',
		'Punta del Este',
		'Rincón del Indio',
		'Ruta 37 y 9',
		'San Carlos',
		'San Francisco',
		'San Vicente',
		'Santa Monica',
		'Sarandi del Mataojo',
		'Sauce de Portezuelo',
		'Solis',
		'Valdivia',
		'Villa Delia'
	),
	'UY-MO' => array(
		'Abayubá',
		'Aguada',
		'Aires Puros',
		'Atahualpa',
		'Bañados de Carrasco',
		'Barrio Sur',
		'Bella Italia',
		'Bella Vista',
		'Belvedere',
		'Brazo Oriental',
		'Buceo',
		'Capra',
		'Capurro',
		'Carrasco',
		'Carrasco Norte',
		'Casabo',
		'Casavalle',
		'Centro',
		'Cerrito',
		'Cerro',
		'Chacarita de los Padres',
		'Ciudad Vieja',
		'Colón',
		'Conciliación',
		'Cordón',
		'Flor de Maroñas',
		'Goes',
		'Ituzaingó',
		'Jacinto Vera',
		'Jardines del Hipódromo',
		'La Blanqueada',
		'La Comercial',
		'La Cruz de Carrasco',
		'La Figurita',
		'La Mondiola',
		'La Paloma',
		'La Teja',
		'Larrañaga',
		'Lavalleja Sur',
		'Las Acacias',
		'Lezica',
		'Malvín',
		'Malvín Norte',
		'Manga',
		'Manga - Toledo Chico',
		'Marconi',
		'Maroñas',
		'Melilla',
		'Mercado Modelo',
		'Miramar',
		'Nuevo París',
		'Pajas Blancas',
		'Palermo',
		'Parque Batlle',
		'Parque Guaraní',
		'Parque Rodó',
		'Paso de la Arena',
		'Paso de las Duranas',
		'Paso Molino',
		'Peñarol',
		'Pérez Castellanos',
		'Piedras Blancas',
		'Plácido Ellauri',
		'Pocitos',
		'Prado',
		'Punta Carretas',
		'Punta Gorda',
		'Punta de Rieles',
		'Reducto',
		'Santa Catalina',
		'Sayago',
		'Tres Cruces',
		'Tres Ombúes',
		'Trouville',
		'Unión',
		'Villa Española',
		'Villa García',
		'Villa Muñoz'
	),
	'UY-PA' => array(
		'Araujo',
		'Arbolito (totoral)',
		'Arroyo Malo',
		'Arroyo Negro',
		'Beisso',
		'Bella Vista',
		'Caada del Pueblo',
		'Carumbe',
		'Casa Blanca',
		'Cerro Chato',
		'Chacras de Paysandu',
		'Chapicuy',
		'Colonia Arroyo Malo',
		'Colonia Cangue',
		'Colonia Juncal',
		'Colonia Paysandu',
		'Colonia Santa Blanca',
		'Colonia Uruguaya',
		'Constancia',
		'Costa de Sacra',
		'Cuchilla de Buricayupi',
		'Cuchilla de Fuego',
		'El Chaco',
		'El Duraznal',
		'El Eucaliptus',
		'El Horno',
		'El Tarugo',
		'Estacion Porvenir',
		'Etchemendi',
		'Gallinal',
		'Gualeguay',
		'Guaviyu de Quebracho',
		'Guayabos',
		'Guichon',
		'La Tentacion',
		'Las Flores',
		'Las Palmas',
		'Lorenzo Geyres',
		'Merinos',
		'Morato (tres Arboles)',
		'Nuevo Paysandu',
		'Orgoroso',
		'Palmar del Quebracho',
		'Parada Dayman',
		'Parada Esperanza',
		'Parada Pandule',
		'Parada Rivas',
		'Paso de los Carros',
		'Paysandu',
		'Perico Moreno',
		'Piedra Sola',
		'Piedras Colora',
		'Piedras Coloradas',
		'Piera',
		'Porvenir',
		'Pueblo Alonzo',
		'Pueblo Esperanza',
		'Pueblo Federacion',
		'Puntas de Arroyo Negro',
		'Puntas de Bacacua',
		'Puntas de Buricayupi',
		'Puntas de Cangue',
		'Puntas de Gualeguay',
		'Puntas de las Isletas',
		'Quebracho',
		'Queguay Grande',
		'Queguayar',
		'Rabon',
		'San Felix',
		'San Francisco',
		'San Mauricio',
		'San Miguel',
		'Santa Kilda',
		'Sauce de Abajo',
		'Sauce del Buricayupi',
		'Sauce del Queguay',
		'Soto',
		'Tambores',
		'Termas de Almiron',
		'Termas de Guaviyu',
		'Tomás Paz',
		'Tres Bocas',
		'Valdez',
		'Villa María (tiatucura)',
		'Zeballos'
	),
	'UY-RN' => array(
		'Algorta',
		'Arroyo Negro',
		'Barrio Anglo',
		'Bellaco',
		'Borges',
		'Caracoles',
		'Colonia el Ombu',
		'Don Esteban',
		'El Abrojal',
		'El Progreso',
		'El Surco',
		'Estacion Francia',
		'Estancia Vichadero',
		'Fray Bentos',
		'La Arena',
		'La Coronilla',
		'La Florida',
		'La Palma',
		'La Unión',
		'Las Caas',
		'Las Flores',
		'Las Fracciones',
		'Las Margaritas',
		'Los Arrayanes',
		'Los Mellizos',
		'Los Ranchos',
		'Mataojo',
		'Menafra',
		'Merinos',
		'Molles de Porrua',
		'Nuevo Berlin',
		'Ombucitos',
		'Palmar Grande',
		'Paso Ramirez',
		'Paso de Balbuena',
		'Paso de Leopoldo',
		'Paso de Soca',
		'Paso de los Cobres',
		'Pauru',
		'Pueblo Grecco',
		'Puntas de Averias',
		'Rolon',
		'San Javier',
		'San Lorenzo',
		'Sanchez',
		'Sanchez Chico',
		'Santa Elisa',
		'Santa Isabel',
		'Santa Rosa',
		'Sarandi',
		'Sarandi de Navarro',
		'Sauce',
		'Tres Bocas',
		'Tres Quintas',
		'Uleste',
		'Valle de Soba',
		'Villa General Borges',
		'Villa María',
		'Yaguarete',
		'Young'
	),
	'UY-RV' => array(
		'Abrojal',
		'Alborada',
		'Amarillo',
		'Arroyo Blanco',
		'Arroyo Sauzal',
		'Ataques',
		'Batoví',
		'Berruti',
		'Blanquillos',
		'Buena Orden Al Norte',
		'Capón Alto',
		'Caraguata',
		'Carpinteria',
		'Cerrillada',
		'Cerro Caqueiro',
		'Cerro Chapeu',
		'Cerro Chato',
		'Cerro Pelado',
		'Cerro Pelado Al Este',
		'Cerro Solito',
		'Cerros Blancos',
		'Cerros de la Calera',
		'Chirca de Caraguata',
		'Coronilla',
		'Coronilla de Corrales',
		'Costas de Cuñapirú',
		'Cruz de San Pedro',
		'Cuchilla Mangueras',
		'Cuchilla de Tres Cerros',
		'Cuchilla de Yaguarí',
		'Curticeiras',
		'Curtume',
		'El Ceibo',
		'El Palmito',
		'Guaviyu',
		'Hospital',
		'La Caillava',
		'La Cerrillada',
		'La Chilca',
		'La Pedrera',
		'Lagos del Norte',
		'Lagunon',
		'Las Flores',
		'Laureles',
		'Los Potreros',
		'Mandubi',
		'Manuel Diaz',
		'Masoller',
		'Minas de Corrales',
		'Minas de Cuñapirú (usinas)',
		'Minas de Zapucay',
		'Moirones',
		'Parada Medina',
		'Paso Amarillo',
		'Paso Ataques',
		'Paso Lapuente',
		'Paso Serpa',
		'Paso de Arriera',
		'Paso de Ataques',
		'Paso de Frontera',
		'Paso de Gaire',
		'Paso de la Calera',
		'Paso del Lagunon',
		'Paso del Puerto',
		'Paso del Tapado',
		'Platón',
		'Pueblo Socorro',
		'Pueblo de los Santos',
		'Puntas de Abrojal',
		'Puntas de Corrales',
		'Puntas de Cuñapirú',
		'Puntas del Yaguarí',
		'Rincón de Amarillo',
		'Rincón de Diniz',
		'Rincón de Moraes',
		'Rincón de Rodriguez',
		'Rincón de Roland',
		'Rincón de Tres Cerros',
		'Rincón de Yaguarí',
		'Rincón de los Castillos',
		'Rivera',
		'San Gregorio',
		'Santa Ernestina',
		'Santa Teresa',
		'Segarra',
		'Tranqueras',
		'Tres Cerros',
		'Tres Puentes',
		'Vichadero',
		'Villa Indart',
		'Yaguarí',
		'Zanja Honda',
		'Zanja Honda de Tranqueras'
	),
	'UY-RO' => array(
		'18 de Julio',
		'19 de Abril',
		'Aguas Dulces',
		'Antoniopolis',
		'Arachania',
		'Balneario la Esmeralda',
		'Barra de Valizas',
		'Barra del Chuy',
		'Barrancas de la Coronilla',
		'Barrio Carpacho',
		'Barrio Pereira',
		'Barrio Torres',
		'Cabo Polonio',
		'Capacho',
		'Castillos',
		'Cebollati',
		'Chuy',
		'Costas de Cebollati',
		'La Aguada y Costa Azul',
		'La Coronilla',
		'La Esmeralda',
		'La Pedrera',
		'La Ribiera',
		'Lascano',
		'Oceania del Polonio',
		'Palmares de la Coronilla',
		'Paralle',
		'Parque Balneario la Paloma',
		'Paso Doa Rosa',
		'Plano 291',
		'Pueblo Nuevo',
		'Puente Valizas',
		'Puerto de los Botes',
		'Puerto la Paloma',
		'Puimayen',
		'Punta Rubia',
		'Punta del Diablo',
		'Rocha',
		'Samuel',
		'San Antonio',
		'San Luis Al Medio',
		'San Sebastian de la Pedrera',
		'Tajamares de la Pedrera',
		'Velazquez'
	),
	'UY-SA' => array(
		'Arenitas Blancas',
		'Balneario Albisu',
		'Belen',
		'Biassini',
		'Bordenave',
		'Campo de Todos',
		'Carumbe',
		'Celeste',
		'Cerrillada',
		'Cerrilladas de Saucedo',
		'Cerro Chato',
		'Cerros de Vera',
		'Chacras de Constitucion',
		'Colonia 18 de Julio',
		'Colonia Itapebi',
		'Colonia Lavalleja',
		'Constitucion',
		'Corral de Piedra',
		'Corralito',
		'Cuchilla de Guaviyu',
		'El Espinillar',
		'El Mellado',
		'Ferreira',
		'Garibaldi',
		'Guaviyu de Arapey',
		'Itapebi',
		'La Bolsa 02',
		'La Bolsa 03',
		'La Viticola',
		'Las Flores',
		'Laureles',
		'Lluveras',
		'Los Orientales',
		'Mataojo Grande',
		'Migliaro',
		'Nueva Hesperides',
		'Olivera',
		'Osimani y Llerena',
		'Palomas',
		'Parada Herreria',
		'Parque Jose Luis',
		'Paso  Valega',
		'Paso Cementerio',
		'Paso Fialho',
		'Paso Nuevo del Arapey',
		'Paso de las Piedras de Arerungua',
		'Paso del Parque del Dayman',
		'Paso del Potrero',
		'Paso del Tapado',
		'Pueblo Biassini',
		'Pueblo Cayetano',
		'Pueblo Celeste',
		'Pueblo Farías',
		'Pueblo Fernandez',
		'Pueblo Quintana',
		'Pueblo Rincón de Valentin',
		'Puntas de Valentin',
		'Rincón de Valentin',
		'Russo',
		'Salto',
		'San Antonio',
		'Sarandi de Arapey',
		'Sauce Chico',
		'Saucedo',
		'Talas de Itapebi',
		'Termas del Arapey',
		'Termas del Dayman',
		'Toro Negro',
		'Tropezon',
		'Tropiezo',
		'Valentin Grande',
		'Zanja de Alcain',
		'Zanja del Tigre'
	),
	'UY-SJ' => array(
		'18 de Julio',
		'Adolfo Scavino',
		'Arroyo Llano',
		'Arroyo de la Virgen',
		'Bella Vista',
		'Boca de Cufre',
		'Boca del Cufre',
		'Caada Grande',
		'Cagancha',
		'Cagancha Chico',
		'Capurro',
		'Carreta Quemada',
		'Ceramicas del Sur',
		'Chamizo',
		'Cololo Tinosa',
		'Colonia America',
		'Colonia Delta',
		'Colonia Dr. Bernardo Etchepare',
		'Colonia Italia',
		'Colonia Juan María Perez',
		'Colonia San Joaquin',
		'Colonia Wilson',
		'Coronilla',
		'Costa del Mauricio',
		'Costas de Pereira',
		'Costas del Sauce',
		'Cruz de los Caminos',
		'Cuchilla Seca',
		'Cuchilla del Vichadero',
		'Delta del Tigre y Villas',
		'Delta el Tigre',
		'Ecilda Paullier',
		'Escudero',
		'Estacion Rodriguez',
		'Fajardo',
		'Fajina',
		'Gonzalez',
		'Guaycuru',
		'Ituzaingo',
		'Jesus María',
		'Juan Soler',
		'Juncal',
		'Kiyu - Ordeig',
		'La Boyada',
		'La Casilla',
		'La Cuchilla',
		'Laurel',
		'Libertad',
		'Mahoma',
		'Mal Abrigo',
		'Mangrullo',
		'Monte Grande',
		'Mundo Azul',
		'Mundo Azul Aguirre',
		'Ordeig',
		'Orillas del Plata',
		'Pachina',
		'Panta',
		'Pantanoso',
		'Parque Postel',
		'Parque Postel Cnel. Adrian Medina',
		'Paso Belastiqui',
		'Paso de Cames',
		'Paso de Mas',
		'Paso de las Piedras',
		'Paso del Carreton',
		'Paso del Guaycuru',
		'Paso del Rey',
		'Pavon',
		'Penino',
		'Perico Perez',
		'Picada Gambetta',
		'Playa Pascual',
		'Pueblo Nuevo',
		'Puntas de Cagancha',
		'Puntas de Chamizo',
		'Puntas de Gregorio',
		'Puntas de Laurel',
		'Puntas de Tropa Vieja',
		'Puntas de Valdez',
		'Radial Ruta 3',
		'Rafael Perazza',
		'Raigon',
		'Rapetti',
		'Rincón de Albano',
		'Rincón de Arazati',
		'Rincón de Arias',
		'Rincón de Buschental',
		'Rincón de Cufre',
		'Rincón de Nazareth',
		'Rincón de la Torre',
		'Rincón del Pino',
		'Rocho',
		'Safici',
		'San Fernando',
		'San Fernando Chico',
		'San Gregorio',
		'San Jose de Mayo',
		'Santa Monica',
		'Sauce',
		'Sauce Chico',
		'Scavino',
		'Tabarez',
		'Tala de Pereira',
		'Tranquera Colorada',
		'Tropas Viejas',
		'Tropezon',
		'Valdez Chico',
		'Villa María',
		'Villa Rives',
		'Zanja Honda'
	),
	'UY-SO' => array(
		'Altos del Perdido',
		'Arenal Chico',
		'Arroyo Grande',
		'Arroyo del Medio',
		'Asencio',
		'Bajos del Perdido',
		'Bequelo',
		'Bizcocho',
		'Buena Vista',
		'Caada Nieto',
		'Caada Paraguaya',
		'Cardona',
		'Castillos',
		'Cerro Alegre',
		'Cerro Vera',
		'Chacras de Dolores',
		'Chacras de Mercedes',
		'Chispas',
		'Cololo',
		'Colonia Concordia',
		'Colonia Diaz',
		'Colonia Santa Clara',
		'Colonia Uruguaya',
		'Concordia',
		'Coquimbo',
		'Corralito',
		'Costa del Aguila',
		'Costas del Perdido',
		'Cuatro Bocas de Buena Vista',
		'Cuchilla del Corralito',
		'Cuchilla del Perdido',
		'Cueva del Tigre',
		'Dolores',
		'Duraznito',
		'Egaa',
		'El Aguila',
		'El Tala',
		'Espinillo',
		'Garula',
		'Grito de Asencio',
		'Jose Enrique Rodo',
		'La Concordia',
		'La Laguna',
		'La Loma',
		'La Palma',
		'La Tabla',
		'Lares',
		'Las Maulas',
		'Lata del Perdido',
		'Maciel',
		'Mercedes',
		'Monzon',
		'Olivera',
		'Palmar',
		'Palmitas',
		'Palo Solo',
		'Parada Suarez',
		'Paso de Ramos',
		'Paso de la Arena',
		'Pedro Chico',
		'Perseverano',
		'Progreso',
		'Pueblo Castillo',
		'Puntas de Arenales',
		'Puntas de Durazno',
		'Puntas de San Salvador',
		'Puntas del Tala',
		'Rincón de Caada Nieto',
		'Rincón de Cololo',
		'Rincón de Ruiz',
		'Risso',
		'Sacachispas',
		'San Dios',
		'San Martin',
		'Santa Blanca',
		'Santa Catalina',
		'Sarandi Chico',
		'Unidad Cooperaria No 1',
		'Villa Alejandrina',
		'Villa Darwin',
		'Villa Soriano',
		'Zanja Honda'
	),
	'UY-TA' => array(
		'Achar',
		'Arroyo del Medio',
		'Ataque',
		'Baado de Rocha',
		'Balneario Ipora',
		'Barrio Libertad',
		'Blanquillos',
		'Caas',
		'Cardoso',
		'Cardozo Chico',
		'Carpinteria',
		'Cerro Batoví',
		'Cerro Chato',
		'Cerro de Pastoreo',
		'Cerro de Pereira',
		'Cerro del Arbolito',
		'Cerros de Clara',
		'Chamberlain',
		'Charata',
		'Churchill',
		'Cinco Sauces',
		'Clara',
		'Clavijo',
		'Colman',
		'Costas de Tres Cruces',
		'Coyo Martinez',
		'Cruz de los Caminos',
		'Cuchilla de Laureles',
		'Cuchilla de Peralta',
		'Cuchilla de la Casa de Piedra',
		'Cuchilla de la Palma',
		'Cuchilla del Ombu',
		'Curtina',
		'El Empalme',
		'Frigorifico Modelo',
		'Heriberto',
		'La Aldea',
		'La Bolsa 01',
		'La Hilera',
		'La Palma',
		'La Pedrera',
		'Lambare',
		'Las Chircas',
		'Las Pajas',
		'Las Toscas de Caraguata',
		'Laureles',
		'Los Cerros',
		'Los Coitinhos',
		'Los Cuadrados',
		'Los Feos',
		'Los Furtados',
		'Los Laureles',
		'Los Rodriguez',
		'Los Rosanos',
		'Los Rosas',
		'Los Semper',
		'Los Vazquez',
		'Martinote',
		'Minuano',
		'Montevideo Chico',
		'Once Cerros',
		'Pampa',
		'Paso Bonilla',
		'Paso Hondo',
		'Paso Victor',
		'Paso de Ceferino',
		'Paso de Perez',
		'Paso de las Carretas',
		'Paso de las Flores',
		'Paso de los Novillos',
		'Paso de los Toros',
		'Paso del Cerro',
		'Paso del Medio',
		'Pasode Lostoros',
		'Picada de Cuello',
		'Piedra Sola',
		'Pueblo de Arriba',
		'Pueblo del Barro',
		'Punta de Carretera',
		'Puntas de Cinco Sauces',
		'Puntas de Laureles',
		'Rincón de Freitas',
		'Rincón de Giloca',
		'Rincón de Pereira',
		'Rincón de Zamora',
		'Rincón de la Aldea',
		'Rincón de la Bolsa',
		'Rincón de la Laguna',
		'Rincón de los Machado',
		'Rincón del Bonete',
		'Rivera Chico',
		'San Benito',
		'San Gregorio de Polanco',
		'San Joaquin',
		'Sauce Solo',
		'Sauce de Batoví',
		'Sauce de Tranqueras',
		'Tacuarembo',
		'Tacuarembo Chico',
		'Tambores',
		'Tierras Coloradas',
		'Turupi',
		'Valle Eden',
		'Villa Ansina',
		'Zambullon',
		'Zapara',
		'Zapucay'
	),
	'UY-TT' => array(
		'Arrocera Bonomo',
		'Arrocera Mini',
		'Arrocera Procipa',
		'Arrocera Rincón',
		'Arrocera San Fernando',
		'Arrocera Santa Fe',
		'Arrocera Zapata',
		'Arrocera el Tigre',
		'Arrocera la Catumbera',
		'Arrocera la Querencia',
		'Arrocera las Palmas',
		'Arrocera los Ceibos',
		'Arrocera los Teros',
		'Arrozal Treinta y Tres',
		'Cerro Chato',
		'Cerro Pelado',
		'Ejido de Treinta y Tres',
		'El Bellaco',
		'Gral. Enrique Martinez',
		'La Charqueada',
		'María Albina',
		'María Isabel',
		'Mendizabal',
		'Palo a Pique',
		'Poblado Alonzo',
		'Pueblo General Enrique Martinez',
		'Pueblo Rincón de Ramirez',
		'Puntas del Parao',
		'Rincón',
		'Santa Clara de Olimar',
		'Treinta y Tres',
		'Tupambae',
		'Valentines',
		'Vergara',
		'Villa María Albina',
		'Villa Passano',
		'Villa Sara'
	)
);
